# Generated by Django 5.0 on 2023-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='Images')),
            ],
        ),
    ]
